# Generated by Django 5.0.1 on 2024-01-31 14:55

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DescriereServicii',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=200, verbose_name='Numele Serviciului')),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preț')),
                ('durata', models.DurationField(verbose_name='Durata')),
                ('descriere', tinymce.models.HTMLField(verbose_name='Descriere')),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='services_images/', verbose_name='Imagine')),
                ('categorie', models.CharField(max_length=100, verbose_name='Categorie')),
                ('available', models.BooleanField(default=True, verbose_name='Disponibil')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Data Adăugării')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizare')),
                ('promotion', models.TextField(blank=True, null=True, verbose_name='Promoții sau Reduceri')),
            ],
            options={
                'verbose_name_plural': 'Descrieri Servicii',
            },
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=100)),
                ('prenume', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=15)),
                ('serviciu', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('ora', models.TimeField()),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
