# Generated by Django 5.0.2 on 2024-03-02 19:13

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0004_alter_descriereservicii_promotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descriereservicii',
            name='promotion',
            field=tinymce.models.HTMLField(blank=True, default='', null=True, verbose_name='Promoții'),
        ),
    ]
