# Generated by Django 5.0.2 on 2024-03-02 19:21

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0005_alter_descriereservicii_promotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespreMine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(blank=True, null=True, upload_to='about_images/', verbose_name='Imagine')),
                ('descriere', tinymce.models.HTMLField(verbose_name='Descriere')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Data Adăugării')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizare')),
            ],
            options={
                'verbose_name_plural': 'Despre Mine',
            },
        ),
    ]
