# Generated by Django 5.0.2 on 2024-03-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0006_despremine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DespreMine',
            new_name='Despre',
        ),
        migrations.AlterModelOptions(
            name='despre',
            options={'verbose_name_plural': 'Despre'},
        ),
    ]
