# Generated by Django 5.0.2 on 2024-03-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0007_rename_despremine_despre_alter_despre_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='despre',
            name='nume',
            field=models.CharField(default='Despre', max_length=100, verbose_name='Nume'),
        ),
    ]
