# Generated by Django 5.0.3 on 2024-03-23 19:52

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0009_remove_programare_content_programare_observatii'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Informații de contact', max_length=100, verbose_name='Nume')),
                ('content', tinymce.models.HTMLField(verbose_name='Conținut')),
                ('email', models.EmailField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=15, verbose_name='Număr de Telefon')),
                ('facebook_page', models.URLField(max_length=255, verbose_name='Pagina de Facebook')),
                ('instagram', models.URLField(max_length=255, verbose_name='Pagina de Instagram')),
                ('address', models.TextField(verbose_name='Adresa Salonului')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Data Adăugării')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizare')),
            ],
            options={
                'verbose_name_plural': 'Informații de contact',
            },
        ),
    ]
