# Generated by Django 5.0.3 on 2024-03-23 20:51

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0010_contactinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programare',
            name='observatii',
            field=tinymce.models.HTMLField(default=False, verbose_name='Observații'),
        ),
    ]
