# Generated by Django 5.0.3 on 2024-03-23 20:53

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0011_alter_programare_observatii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programare',
            name='observatii',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Observații'),
        ),
    ]
