# Generated by Django 5.0.3 on 2024-03-24 08:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0012_alter_programare_observatii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programare',
            name='telefon',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Numărul de telefon trebuie să fie introdus în formatul: '+999999999'. Permise până la 15 cifre.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Număr de Telefon'),
        ),
    ]
