# Generated by Django 5.0.3 on 2024-03-24 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0013_alter_programare_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programare',
            name='telefon',
            field=models.CharField(max_length=15, null=True, validators=[django.core.validators.RegexValidator(message="Numărul de telefon trebuie să contina doar cifre în formatul: '000 000 000'. Permise până la 15 cifre.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Număr de Telefon'),
        ),
    ]
