# Generated by Django 5.0.3 on 2024-04-14 14:57

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salon', '0014_alter_programare_telefon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politica_Confidentialitate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(default='Politica de Confidențialitate', max_length=100, verbose_name='Nume')),
                ('continut', tinymce.models.HTMLField(verbose_name='Conținut')),
                ('added_on', models.DateTimeField(auto_now_add=True, verbose_name='Data Adăugării')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Ultima Actualizare')),
            ],
            options={
                'verbose_name_plural': 'Politica de Confidențialitate',
            },
        ),
    ]
